---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service-monitor
  namespace: medrobotics
  labels:
    app: api-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api-service
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-ingestion-monitor
  namespace: medrobotics
  labels:
    app: data-ingestion
    release: prometheus
spec:
  selector:
    matchLabels:
      app: data-ingestion
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
